name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.7.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'ahojukka5-maidentiedot-backend'
          heroku_email: 'ahojukka5@gmail.com'
        env:
          NODE_ENV: production
          WEATHER_API_ACCESS_KEY: ${{ secrets.WEATHER_API_ACCESS_KEY }}
